---

- hosts: 127.0.0.1
  connection: local
  roles:
    - local

- hosts: all
  user: vagrant
  sudo: yes
  roles:
   - common

# - hosts: rabbitmq
#   user: vagrant
#   sudo: yes
#   roles:
#    - rabbitmq

# - hosts: redis
#   user: vagrant
#   sudo: yes
#   roles:
#    - redis

# - hosts: sensu
#   user: vagrant
#   sudo: yes
#   roles:
#    - sensu

- hosts: elasticsearch
  user: vagrant
  sudo: yes
  roles:
   - elasticsearch
